/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get monitoring metric feeds */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Monitoring metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonitoringFeedsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List instrument categories and models */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Instrument catalog */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstrumentsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update instrument selection or connection */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateInstrumentPayload"];
                };
            };
            responses: {
                /** @description Updated category (平铺 — live 实现不包 category 层, P3-17 G11) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstrumentCategory"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}/topology-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Operator selects (or clears) the topology profile for a binding (P2-1)
         * @description P3-17 G11: 本操作曾错挂在复数集合路径 /topology-profiles 上 — live
         *     实现的选择端点是单数 /topology-profile (集合路径只有 GET/POST)。
         *     - `profile_id=null` clears the selection.
         *     - `profile_id="known_id"` with no live driver: persists; takes
         *       effect on next HAL reload.
         *     - `profile_id="known_id"` + live driver + compatible: persists
         *       AND immediately applies on the driver. Response carries
         *       `applied_now=true`.
         *     - `profile_id="known_id"` + live driver + INCOMPATIBLE: returns
         *       409 with `refused: true` + structured reason. Binding is NOT
         *       persisted (refuses bail before DB write so operator can't
         *       save a doomed selection). Matches the P2-5 refuse pattern.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SelectTopologyProfileRequest"];
                };
            };
            responses: {
                /** @description Selection persisted (and optionally applied) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SelectTopologyProfileResult"];
                    };
                };
                /** @description Category, connection, or profile_id not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Topology incompatible with detected Test App */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}/topology-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List operator-selectable topology profiles for a binding (P2-1)
         * @description Two-layer UXM architecture (P2-1 Phase 1):
         *     - Test App layer = SCPI command vocabulary, AUTO-DETECTED at
         *       connect via `SYSTem:APPLication:NAME?`. Operator does not pick.
         *     - Topology profile layer = cell/MIMO/power/FRC configuration
         *       within the running Test App. Operator-picked, persisted in
         *       `InstrumentConnection.connection_params['topology_profile_id']`,
         *       auto-applied on HAL reload.
         *     The `compatible_with_current_test_app` flag per item reflects
         *     the live HAL driver's detected_test_app — GUI greys out
         *     incompatible options. Empty `compatible_test_apps` on a profile
         *     means "compatible with any Test App" (no constraint).
         *     Only `baseStation` category exposes profiles today (UXM
         *     specific); other categories return empty + `reason="not_a_uxm"`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Topology profile list + live compat status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfilesListResult"];
                    };
                };
                /** @description Category not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create a new operator-owned topology profile (P2-1 Phase 2.1)
         * @description `profile_id` is auto-allocated (`custom_<slug>`) — operators
         *     don't pick raw IDs (prevents collisions with built-ins and
         *     slug-formatting surprises). Returns the full row including the
         *     assigned ID so the GUI can pre-select it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTopologyProfileRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfileDetail"];
                    };
                };
                /** @description Bad request — empty name or unknown field */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Category does not host topology profiles */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}/topology-profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full detail for a single topology profile (P2-1 Phase 2.2)
         * @description Returns the full 25+ field row so the GUI editor modal can
         *     populate the form. The list endpoint returns only the
         *     truncated `TopologyProfileEntry`; this endpoint returns the
         *     full `TopologyProfileDetail`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full profile detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfileDetail"];
                    };
                };
                /** @description Profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Update an operator-owned topology profile (P2-1 Phase 2.1)
         * @description Partial-update. Refuses `is_system_preset=true` rows with 409 —
         *     operator must duplicate first. Unknown field keys return 400.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTopologyProfileRequest"];
                };
            };
            responses: {
                /** @description Updated row */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfileDetail"];
                    };
                };
                /** @description Bad request — unknown field */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description System preset — duplicate to edit */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delete an operator-owned topology profile (P2-1 Phase 2.1)
         * @description Refuses `is_system_preset=true` rows with 409. Does NOT touch
         *     bindings — if a category has the profile bound via
         *     `connection_params['topology_profile_id']`, that selection
         *     silently becomes stale on next HAL reload (HAL warns + skips
         *     auto-apply). GUI should warn before delete if bindings exist.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description System preset — cannot delete */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}/topology-profiles/{profileId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone any topology profile into a new editable copy (P2-1 Phase 2.1)
         * @description Supported source for both system presets and operator-owned
         *     rows. The new copy has `is_system_preset=false` (always) and
         *     a `(副本)` suffix on the name so it's visually distinct in the
         *     dropdown. Useful for the GUI's "duplicate-to-edit" flow on a
         *     system preset.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New editable copy */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfileDetail"];
                    };
                };
                /** @description Source profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/hal/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * HAL composite readiness snapshot (P3-5)
         * @description Returns HAL-owned per-driver rows from the last initialise / reload
         *     together with request-time LabProfile and calibration readiness.
         *     An explicit `lab_profile_id` selects that exact active profile;
         *     omitting it keeps the unique-active compatibility behaviour.
         *     `available=false` means HAL-owned driver/subnet data is unavailable,
         *     while the database-only LabProfile and calibration sections remain live.
         *     Sibling HAL endpoints (`/hal/status`, `/hal/reload`, `/hal/switch`)
         *     are not currently in this contract; the GUI consumes them via
         *     inline-typed `axios.get`. Bringing them under generated types is
         *     out of scope for P3-5.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Current browser-selected active LabProfile; no implicit fallback when supplied. */
                    lab_profile_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Readiness snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HALReadinessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List execution history (ARCH-1 S2, sourced from test_executions)
         * @description One row per execution from the test_executions table itself
         *     (case-runner / commissioning / diagnostics; VRT rows excluded),
         *     newest first by executed_at. Includes RUNNING rows — the test case
         *     library uses status=running to restore the active-run badge after
         *     navigation (Codex #237 C3). Row id is TestExecution.id and can be
         *     passed directly as a report's test_execution_ids.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    skip?: number;
                    /**
                     * @description Row status. Covers every value test_executions.status can hold
                     *     for non-VRT rows: pending (session row not yet run), running,
                     *     completed, failed, cancelled, skipped (ad-hoc phase skipped).
                     */
                    status?: "pending" | "running" | "completed" | "failed" | "cancelled" | "skipped";
                    /**
                     * @description Filter by execution chain (test_case_runner / test_plan_runner /
                     *     commissioning_api / commissioning_adhoc). Repeatable — pass the
                     *     parameter once per chain to match any of them.
                     *
                     *     Narrowing MUST happen here rather than client-side: client-side
                     *     filtering runs after the limit window, so a chain with many rows
                     *     crowds out the wanted ones. Two instances so far — the case
                     *     library's active-run recovery passes test_case_runner (stale
                     *     plan-runner running rows would crowd it out), and the
                     *     pending-report list passes the three formal chains (ad-hoc
                     *     diagnostics would crowd out archivable executions).
                     */
                    executed_by?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Execution history page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestExecutionListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-plans/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reusable TestCases */
        get: {
            parameters: {
                query?: {
                    skip?: number;
                    limit?: number;
                    test_type?: string;
                    is_template?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description TestCase page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestCaseListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a reusable TestCase */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TestCaseCreate"];
                };
            };
            responses: {
                /** @description Created TestCase */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestCaseResponse"];
                    };
                };
                /** @description Invalid TestCase payload */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-plans/cases/{test_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        /** Get one TestCase */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    test_case_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description TestCase detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestCaseResponse"];
                    };
                };
                /** @description TestCase not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete one TestCase */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    test_case_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description TestCase deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description TestCase not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update one TestCase */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    test_case_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TestCaseUpdate"];
                };
            };
            responses: {
                /** @description Updated TestCase */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestCaseResponse"];
                    };
                };
                /** @description TestCase not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid TestCase payload */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/test-plans/cases/executions/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one TestCase execution status and sanitized SCPI evidence */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    execution_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Execution status with P1-47C evidence when available */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CaseExecutionStatus"];
                    };
                };
                /** @description Execution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system-logs/tail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tail a structured log file (P2-8 cockpit log zone)
         * @description Reverse-scans a JSON-lines log file from the end, applying the
         *     optional level / keyword / session filters during the scan, until
         *     N matching entries are collected (or a bounded scan limit is hit).
         *     With filters active the window is therefore "newest N matching
         *     lines", so sparse WARNING/ERROR entries are not flushed out by
         *     high-frequency INFO noise.
         */
        get: {
            parameters: {
                query?: {
                    filename?: string;
                    lines?: number;
                    /** @description Comma-separated set of levels (e.g. `WARNING,ERROR,CRITICAL`). Exact membership match, NOT a threshold — ZoneLogsAlerts' cross-stream dedup relies on level streams being disjoint; do not change to >=. */
                    level?: string;
                    /** @description Fuzzy match against msg + logger + the same-line `exception` field (where JsonFormatter puts tracebacks) + RAW continuation lines of the group; a hit anywhere returns the whole group (parent + continuations). */
                    keyword?: string;
                    /** @description Exact match on the per-request correlation id */
                    session_id?: string;
                    /** @description Exact match on the per-test-execution correlation id. Distinct from session_id: one execution spans multiple requests and may run outside any request (background task). */
                    execution_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Parsed tail page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemLogTailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system-logs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read an explicitly requested older log page (P1-43)
         * @description Continues a reverse scan from the opaque cursor returned by `/tail`
         *     or a previous history page. This endpoint is for explicit operator
         *     actions only and must not be placed on the live polling path. An empty
         *     filtered page can still return a newer cursor so sparse matches remain
         *     reachable without an unbounded single request.
         */
        get: {
            parameters: {
                query: {
                    /** @description Opaque continuation cursor returned by the server */
                    cursor: string;
                    filename?: string;
                    lines?: number;
                    /** @description Comma-separated exact-match level set */
                    level?: string;
                    /** @description Same scope as /tail keyword (msg + logger + same-line exception + RAW continuations; whole group returned) */
                    keyword?: string;
                    session_id?: string;
                    execution_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One older log page and its continuation cursor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemLogTailResponse"];
                    };
                };
                /** @description Malformed or unsupported cursor */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cursor no longer matches the selected log snapshot */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active alerts ordered by severity (P2-8 cockpit alert zone) */
        get: {
            parameters: {
                query?: {
                    /** @description Defaults to active when omitted */
                    status?: string;
                    severity?: "info" | "warning" | "error" | "critical";
                    limit?: number;
                    skip?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alert page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardAlertListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/alerts/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active-alert counts by severity (P2-8 cockpit alert tally) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alert summary counts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardAlertSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channel-assets/vendor-files/smu-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview mounted F64 .smu project truth
         * @description Read-only bounded scan of the server-configured SMB mount. The client cannot submit a path, frequency, ARFCN, or cached preview.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exact-path synchronization preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SMUProjectSyncPreviewResponse"];
                    };
                };
                /** @description Scan configuration missing, ambiguous, unsafe, or bounded scan failed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channel-assets/vendor-files/smu-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synchronize mounted F64 .smu project truth
         * @description Re-scans server-side and atomically updates only exact, registered, provable matches. The client cannot supply truth in a request body.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Synchronization result and post-commit preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SMUProjectSyncResultResponse"];
                    };
                };
                /** @description Scan or synchronization failed without partial writes */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration/path-loss/rf-chain/uplink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start RF chain uplink gain calibration (P1-68 real reachable) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartRFChainCalibrationRequest"];
                };
            };
            responses: {
                /** @description Calibration job result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalibrationJobResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration/path-loss/rf-chain/downlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start RF chain downlink gain calibration (P1-68 real reachable) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartRFChainCalibrationRequest"];
                };
            };
            responses: {
                /** @description Calibration job result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalibrationJobResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration/path-loss/multi-frequency/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start multi-frequency path-loss calibration (real = CE+SA sweep) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartMultiFrequencyPathLossRequest"];
                };
            };
            responses: {
                /** @description Calibration job result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalibrationJobResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration/phase/calibrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Phase calibration entry (fail-loud closed since P1-68) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PFS is power-only (TR 37.977 F.2); phase calibration belongs to a future PWS. Entry refuses and no mock rows are generated. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration/probe/phase/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe phase calibration mock entry (fail-loud closed since P1-68) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mock-generation entry closed; external measured phase data must go through POST /api/v1/calibration/probe/phase/import-csv. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StartRFChainCalibrationRequest: {
            /** Format: uuid */
            chamber_id: string;
            /** @enum {string} */
            chain_type: "uplink" | "downlink";
            frequency_mhz: number;
            vna_id?: string | null;
            power_meter_id?: string | null;
            signal_generator_id?: string | null;
            probe_ids?: number[] | null;
            calibrated_by: string;
            /**
             * @description True = simulated data (default). False = real instrument path. P1-68 restored API reachability; the RFChain real branch is VNA+SG based and its measurement route is pending the P1-69 decision (CE+SA policy).
             * @default true
             */
            use_mock: boolean;
        };
        StartMultiFrequencyPathLossRequest: {
            /** Format: uuid */
            chamber_id: string;
            probe_ids: number[];
            polarization: string;
            freq_start_mhz: number;
            freq_stop_mhz: number;
            freq_step_mhz: number;
            sgh_model: string;
            sgh_gain_dbi: number;
            vna_id?: string | null;
            calibrated_by: string;
            /**
             * @description True = simulated (default); False = real CE+SA frequency sweep (_real_frequency_sweep_via_ce_sa). P1-68 restored reachability.
             * @default true
             */
            use_mock: boolean;
        };
        CalibrationJobResponse: {
            /** Format: uuid */
            calibration_job_id: string;
            status: string;
            estimated_duration_minutes?: number | null;
            message?: string | null;
            warnings?: string[];
        };
        SMUProjectSyncItemResponse: {
            relative_path: string;
            instrument_path: string;
            size_bytes: number;
            sha256: string;
            center_frequencies_hz: {
                [key: string]: number;
            };
            primary_center_frequency_hz?: number | null;
            scan_status: string;
            scan_detail?: string | null;
            sync_status: string;
            sync_detail: string;
            /** Format: uuid */
            connection_id: string;
            /** Format: uuid */
            asset_id?: string | null;
            asset_name?: string | null;
            target_arfcn?: number | null;
        };
        SMUProjectSyncPreviewResponse: {
            /** Format: uuid */
            connection_id: string;
            items: components["schemas"]["SMUProjectSyncItemResponse"][];
            protected_paths: string[];
            total_files: number;
            total_bytes: number;
        };
        SMUProjectSyncResultResponse: {
            updated_count: number;
            already_synced_count: number;
            preview: components["schemas"]["SMUProjectSyncPreviewResponse"];
        };
        TestCaseCreate: {
            name: string;
            description?: string | null;
            test_type: string;
            configuration: {
                [key: string]: unknown;
            };
            pass_criteria?: {
                [key: string]: unknown;
            } | null;
            expected_results?: {
                [key: string]: unknown;
            } | null;
            probe_selection?: {
                [key: string]: unknown;
            } | null;
            instrument_config?: {
                [key: string]: unknown;
            } | null;
            channel_model?: string | null;
            channel_parameters?: {
                [key: string]: unknown;
            } | null;
            frequency_mhz?: number | null;
            tx_power_dbm?: number | null;
            bandwidth_mhz?: number | null;
            test_duration_sec?: number | null;
            /**
             * Format: uuid
             * @description LabProfile targeted by this TestCase. Null keeps the case
             *     deployment-agnostic and requires a unique active LabProfile at execution time.
             */
            lab_profile_id?: string | null;
            /** @default false */
            is_template: boolean | null;
            template_category?: string | null;
            created_by: string;
            tags?: string[] | null;
        };
        TestCaseUpdate: {
            name?: string | null;
            description?: string | null;
            configuration?: {
                [key: string]: unknown;
            } | null;
            pass_criteria?: {
                [key: string]: unknown;
            } | null;
            expected_results?: {
                [key: string]: unknown;
            } | null;
            probe_selection?: {
                [key: string]: unknown;
            } | null;
            instrument_config?: {
                [key: string]: unknown;
            } | null;
            channel_model?: string | null;
            channel_parameters?: {
                [key: string]: unknown;
            } | null;
            frequency_mhz?: number | null;
            tx_power_dbm?: number | null;
            bandwidth_mhz?: number | null;
            test_duration_sec?: number | null;
            /**
             * Format: uuid
             * @description LabProfile targeted by this TestCase; explicit null clears the binding.
             */
            lab_profile_id?: string | null;
            tags?: string[] | null;
        };
        TestCaseResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            test_type: string;
            configuration: {
                [key: string]: unknown;
            };
            pass_criteria: {
                [key: string]: unknown;
            } | null;
            expected_results: {
                [key: string]: unknown;
            } | null;
            probe_selection: {
                [key: string]: unknown;
            } | null;
            instrument_config: {
                [key: string]: unknown;
            } | null;
            channel_model: string | null;
            channel_parameters: {
                [key: string]: unknown;
            } | null;
            frequency_mhz: number | null;
            tx_power_dbm: number | null;
            bandwidth_mhz: number | null;
            test_duration_sec: number | null;
            /** Format: uuid */
            lab_profile_id: string | null;
            is_template: boolean;
            template_category: string | null;
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: string;
            /** Format: uuid */
            parent_id: string | null;
            tags: string[] | null;
        };
        TestCaseSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            test_type: string;
            template_category?: string | null;
            channel_model?: string | null;
            frequency_mhz?: number | null;
            bandwidth_mhz?: number | null;
            test_duration_sec?: number | null;
            is_template: boolean;
            pass_criteria?: {
                [key: string]: unknown;
            } | null;
            tags?: string[] | null;
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        TestCaseListResponse: {
            total: number;
            items: components["schemas"]["TestCaseSummary"][];
        };
        DashboardResponse: {
            summary: components["schemas"]["DashboardSummary"];
            recent_tests: components["schemas"]["RecentTestItem"][];
            active_alerts: components["schemas"]["AlertItem"][];
            live_metrics: components["schemas"]["MetricItem"][];
        };
        DashboardSummary: {
            probe_count: number;
            active_alerts: number;
            comparisons_selected: number;
        };
        RecentTestItem: {
            id?: string;
            plan_name?: string;
            status?: string;
            executed_at?: string;
            duration_minutes?: number | null;
        };
        MonitoringFeedsResponse: {
            feeds: components["schemas"]["MetricItem"][];
        };
        InstrumentsResponse: {
            categories: components["schemas"]["InstrumentCategory"][];
        };
        UpdateInstrumentPayload: {
            modelId?: string | null;
            connection?: components["schemas"]["InstrumentConnection"];
        };
        SystemStatusItem: {
            label: string;
            value: string;
            detail: string;
        };
        AlertItem: {
            id: string;
            title: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            timestamp: string;
        };
        MetricItem: {
            id?: string;
            label: string;
            value: string;
            trend?: string;
        };
        InstrumentCategory: {
            categoryId: string | null;
            key: string;
            label: string;
            description: string;
            tags: string[];
            selectedModelId: string | null;
            connection: components["schemas"]["InstrumentConnection"];
            models: components["schemas"]["InstrumentModel"][];
            /** @default true */
            isActive: boolean;
            /** @default [] */
            usagePhase: string[];
            /** @default auto */
            driverMode: string;
        };
        InstrumentModel: {
            id: string;
            vendor: string;
            model: string;
            summary: string;
            interfaces: string[];
            capabilities: string[];
            /**
             * @description P2-3: canonical capability tokens this model CAN expose
             *     (per DriverClass.model_capabilities ClassVar). Distinct
             *     from the freeform datasheet-derived `capabilities` badges
             *     above. Empty list means either no real driver is
             *     registered for the model, or the driver intentionally
             *     declared no tokens. Used by GUI to gate plan-binding
             *     picks before HAL Reload (closes the P1-1 pre-flight gap
             *     of needing a connected driver to know what it'd support).
             * @default []
             */
            model_capabilities: string[];
            bandwidth: string | null;
            channels: string | null;
            /**
             * @description Catalog availability status.
             *     - `available`: real driver class registered + HAL can bring it up
             *     - `pending_dev`: catalog row exists but no real driver class
             *       is registered yet (`_convert_model` in `app/api/instrument.py`
             *       maps to this when `get_real_driver_class()` returns None).
             *       Operators picking a model must see this distinctly so they do
             *       not try to connect to a model that has no registered driver.
             * @enum {string}
             */
            status: "available" | "pending_dev";
        };
        InstrumentConnection: {
            id: string | null;
            endpoint: string | null;
            controller: string | null;
            notes: string | null;
            connection_params: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description P3-5 composite snapshot. `available=false` means HAL is not
         *     initialised; sub-sections still carry valid shapes (with
         *     placeholder values) so the GUI never has to handle a 404 or
         *     missing-field path.
         */
        HALReadinessResponse: {
            available: boolean;
            drivers: components["schemas"]["DriverReadinessRow"][];
            lab_profile: components["schemas"]["LabProfileReadiness"];
            calibration: components["schemas"]["CalibrationReadiness"];
            dut_attach: components["schemas"]["DutAttachReadiness"];
            generated_at_iso: string;
            /**
             * @description P1-11: per-/24-subnet reachability rollup derived from the
             *     driver rows. Empty when HAL hasn't initialised or no driver
             *     carries a parseable IP.
             * @default []
             */
            subnets: components["schemas"]["SubnetReachability"][];
        };
        DriverReadinessRow: {
            category: string;
            model: string;
            endpoint: string;
            /** @enum {string} */
            status: "ok" | "warn" | "fail" | "skipped";
            detail: string;
            /**
             * @description P1-11: when `status == fail`, why. `network` = TCP preflight
             *     couldn't reach the host (most likely wrong /24 subnet);
             *     `scpi` = TCP reached but the driver session / *IDN? failed
             *     (instrument/session problem). `null` whenever status != fail.
             * @enum {string|null}
             */
            fail_kind: "network" | "scpi" | null;
            /**
             * @description Driver-specific metadata (string-keyed). F64 surfaces
             *     firmware_version / band_label / product_family from the
             *     parsed SYST:INFO? response (P3-4); other drivers return an
             *     empty object until they override `readiness_metadata()`.
             *     Field values may be null when a driver field is unpopulated.
             * @default {}
             */
            extras: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Active LabProfile state. `status` distinguishes "no profiles at
         *     all" (`missing`) from "profiles exist but none active"
         *     (`inactive`) — different operator next-steps.
         */
        LabProfileReadiness: {
            profile_id: string | null;
            profile_name: string | null;
            is_active: boolean;
            /** @enum {string} */
            status: "ok" | "inactive" | "missing" | "ambiguous";
            detail: string;
        };
        /**
         * @description Validity of the active lab's bound calibration certificate.
         *     `no_lab` (no lab to look at a cert through) is distinct from
         *     `missing` (lab exists but cert FK is NULL) — the former hints
         *     "set up lab first", the latter hints "run calibration".
         */
        CalibrationReadiness: {
            certificate_number: string | null;
            valid_until_iso: string | null;
            /** @enum {string} */
            status: "valid" | "expired" | "missing" | "no_lab";
            days_remaining: number | null;
            detail: string;
        };
        /**
         * @description DUT-attach state — placeholder in this build. `status` is
         *     always `not_implemented` since no runtime model exists for
         *     "DUT present in chamber" (no probe-sensing / RFID / session
         *     table). Field is in the contract so future probe-sensing
         *     work can land without breaking the response shape.
         */
        DutAttachReadiness: {
            /** @enum {string} */
            status: "not_implemented";
            detail: string;
        };
        /**
         * @description P1-11/P1-13: per-/24-subnet reachability rollup. Tri-state via
         *     (`probed`, `reachable`): `probed=false` → no instrument on this subnet
         *     was actually network-probed (mock-HAL mode, or bindings with no
         *     parseable host:port) → 未探测/unknown, `reachable` is meaningless (do
         *     NOT render reachable); `probed=true && reachable=false` → ≥1 preflight
         *     timed out (no route); `probed=true && reachable=true` → probed alive.
         *     `hint` is a runbook-pointing string for unreachable subnets, `null`
         *     otherwise. The sentinel cidr `unknown` buckets rows whose endpoint had
         *     no parseable IPv4 host.
         */
        SubnetReachability: {
            /** @description /24 CIDR (e.g. 192.168.0.0/24) or the sentinel "unknown" */
            cidr: string;
            reachable: boolean;
            instrument_count: number;
            unreachable_count: number;
            hint: string | null;
            /** @description P1-13: was any instrument on this subnet actually network-probed? false → 未探测/unknown. */
            probed: boolean;
        };
        /**
         * @description ARCH-1 S2: one execution row from the test_executions table itself
         *     (case-runner / plan-runner step / commissioning / ad-hoc diagnostic;
         *     VRT rows excluded via mode IS NULL). Includes running rows. Mirrors
         *     api-service ExecutionHistoryItem. phases_* null = that execution
         *     chain does not record phase progress; validation_pass null = not
         *     judged.
         */
        TestExecutionItem: {
            id: string;
            case_name: string | null;
            source_test_case_id: string | null;
            status: string;
            phases_total: number | null;
            phases_done: number | null;
            phases_failed: number | null;
            duration_sec: number | null;
            started_at: string | null;
            completed_at: string | null;
            executed_by: string | null;
            error_message: string | null;
            validation_pass: boolean | null;
            /** @description P2-34: execution-failure alert publication outcome recorded on this row (published | duplicate | failed). null = not recorded (rows predating P2-34 / record write failed / not applicable) — null does NOT mean the alert was published. */
            failure_alert_outcome: string | null;
        };
        TestExecutionListResponse: {
            total: number;
            items: components["schemas"]["TestExecutionItem"][];
        };
        ScpiEvidenceEnvironment: {
            instrument_id: string;
            instrument: string;
            model?: string | null;
            firmware_version?: string | null;
            captured_from_live_connection: boolean;
        } & {
            [key: string]: unknown;
        };
        ScpiEvidenceRequirement: {
            requirement_id: string;
            evidence_key: string;
            requested: unknown;
            /** @enum {string} */
            required_evidence_level: "E0" | "E1" | "E2" | "E3" | "E4";
        };
        ScpiEvidenceItem: {
            requirement_id: string;
            instrument: string;
            evidence_key: string;
            requested: unknown;
            command_sent: string | null;
            readback: unknown;
            exchange_ids: string[];
            /** @enum {string} */
            evidence_level: "E0" | "E1" | "E2" | "E3" | "E4";
            source_reference: string | null;
            /** @enum {string} */
            verdict: "passed" | "rejected" | "unknown";
            reason: string;
        };
        /**
         * @description Sanitized P1-47C summary. Raw replies stay in scpi.log and are linked
         *     by execution_id + exchange_ids. Any missing/unknown/rejected mandatory
         *     item makes formal_acceptance false.
         */
        ExecutionScpiEvidence: {
            schema_version: number;
            /** Format: uuid */
            execution_id: string;
            environments: {
                [key: string]: components["schemas"]["ScpiEvidenceEnvironment"];
            };
            required: components["schemas"]["ScpiEvidenceRequirement"][];
            items: components["schemas"]["ScpiEvidenceItem"][];
            missing_requirements: string[];
            /** @enum {string} */
            formal_verdict: "passed" | "rejected" | "unknown";
            formal_acceptance: boolean;
            reason: string;
        };
        CaseExecutionStatus: {
            /** Format: uuid */
            execution_id: string;
            status: string;
            source_test_case_id?: string | null;
            phase_progress: {
                [key: string]: unknown;
            }[];
            failed_phase?: string | null;
            error_message?: string | null;
            started_at?: string | null;
            completed_at?: string | null;
            scpi_evidence?: components["schemas"]["ExecutionScpiEvidence"] | null;
        };
        /**
         * @description P2-8: one parsed log line. `level` is RAW for non-JSON continuation
         *     lines (e.g. Python traceback follow-ups). `raw` holds the original
         *     JSON line for detail expansion.
         */
        SystemLogEntry: {
            ts: string;
            level: string;
            logger: string;
            hal_mode: string;
            session_id: string;
            execution_id: string;
            instrument_id: string;
            msg: string;
            raw: string | null;
        };
        SystemLogTailResponse: {
            filename: string;
            total_lines_read: number;
            filtered_count: number;
            entries: components["schemas"]["SystemLogEntry"][];
            /** @description Opaque cursor for the next older page; null at file start */
            older_cursor: string | null;
            /** @description Whether an explicit history request can continue */
            has_older: boolean;
        };
        /**
         * @description P2-8: one alert row. Mirrors api-service AlertResponse. `severity`
         *     is the operator-facing color key (info < warning < error < critical).
         */
        DashboardAlert: {
            id: string;
            title: string;
            message?: string | null;
            /** @enum {string} */
            severity: "info" | "warning" | "error" | "critical";
            alert_type?: string | null;
            source?: string | null;
            status: string;
            is_read: boolean;
            related_entity_type?: string | null;
            related_entity_id?: string | null;
            created_at: string;
            updated_at: string;
            acknowledged_at?: string | null;
            resolved_at?: string | null;
            created_by?: string | null;
            acknowledged_by?: string | null;
        };
        DashboardAlertListResponse: {
            total: number;
            alerts: components["schemas"]["DashboardAlert"][];
        };
        DashboardAlertSummary: {
            total_active: number;
            info_count: number;
            warning_count: number;
            error_count: number;
            critical_count: number;
        };
        /**
         * @description P2-1: one row in the topology profile listing.
         *     `compatible_with_current_test_app` is null when there's no
         *     live driver to check against (HAL not initialised, mock mode,
         *     no UXM driver bound) — GUI should treat null as "unknown,
         *     allow selection but warn".
         */
        TopologyProfileEntry: {
            profile_id: string;
            name: string;
            description: string;
            category: string;
            compatible_test_apps: string[];
            compatible_with_current_test_app?: boolean | null;
            /**
             * @description P2-1 Phase 2.1: true for the 7 built-ins seeded by the
             *     bootstrap seeder. GUI renders these as read-only with a
             *     'duplicate to edit' affordance (clone-to-edit pattern).
             */
            is_system_preset?: boolean;
        };
        TopologyProfilesListResult: {
            items: components["schemas"]["TopologyProfileEntry"][];
            current_test_app?: string | null;
            selected_topology_profile_id?: string | null;
            /**
             * @description `"not_a_uxm"` when the category doesn't host topology
             *     profiles (today everything except baseStation); otherwise
             *     null. Future categories (CMX500 etc.) extend the dispatch
             *     in `_list_topology_profiles_for_category`.
             */
            reason?: string | null;
        };
        SelectTopologyProfileRequest: {
            /**
             * @description Topology profile ID to bind to this category. Null clears
             *     the selection so HAL reload won't auto-apply anything.
             */
            profile_id?: string | null;
        };
        SelectTopologyProfileResult: {
            persisted: boolean;
            profile_id?: string | null;
            applied_now: boolean;
            /**
             * @description Non-null when the binding was persisted but the driver
             *     was NOT live-applied. Values: `no_selection` (cleared),
             *     `no_live_driver` (HAL not initialised), `driver_does_not_support_topology_profiles`
             *     (e.g. mock driver), `incompatible_test_app` (compat check
             *     failed at the driver level — usually caught earlier as 409).
             */
            apply_skipped_reason?: string | null;
            test_app?: string | null;
        };
        /**
         * @description P2-1 Phase 2.1: full topology profile row returned by CRUD
         *     endpoints (create / update / duplicate). Mirrors the
         *     `UxmTestProfile` dataclass + DB columns.
         */
        TopologyProfileDetail: {
            profile_id: string;
            name: string;
            description?: string | null;
            category: string;
            band: string;
            frequency_mhz: number;
            bandwidth_mhz: number;
            scs_khz: number;
            duplex: string;
            arfcn?: number | null;
            mimo_layers: number;
            mimo_port_preset: string;
            dl_power_dbm: number;
            ssb_power_dbm: number;
            modulation: string;
            target_mcs: number;
            sched_algo: string;
            enable_amc: boolean;
            tdd_pattern: string;
            tdd_period: string;
            harq_max_trans: number;
            harq_processes: number;
            csi_rs_ports?: number | null;
            stat_count: number;
            cell_id: string;
            state_file?: string | null;
            compatible_test_apps: string[];
            notes?: string | null;
            is_system_preset: boolean;
            created_by?: string | null;
        };
        /**
         * @description P2-1 Phase 2.1: POST payload. `name` required; everything else
         *     falls back to dataclass defaults. profile_id is auto-allocated
         *     as `custom_<slug>` so the operator doesn't pick raw IDs.
         */
        CreateTopologyProfileRequest: {
            name: string;
            description?: string | null;
            category?: string | null;
            band?: string | null;
            frequency_mhz?: number | null;
            bandwidth_mhz?: number | null;
            scs_khz?: number | null;
            duplex?: string | null;
            arfcn?: number | null;
            mimo_layers?: number | null;
            mimo_port_preset?: string | null;
            dl_power_dbm?: number | null;
            ssb_power_dbm?: number | null;
            modulation?: string | null;
            target_mcs?: number | null;
            sched_algo?: string | null;
            enable_amc?: boolean | null;
            tdd_pattern?: string | null;
            tdd_period?: string | null;
            harq_max_trans?: number | null;
            harq_processes?: number | null;
            csi_rs_ports?: number | null;
            stat_count?: number | null;
            cell_id?: string | null;
            state_file?: string | null;
            compatible_test_apps?: string[] | null;
            notes?: string | null;
            created_by?: string | null;
        };
        /**
         * @description P2-1 Phase 2.1: PUT payload — all fields optional. Same field
         *     allowlist as Create minus `created_by` (audit field, immutable
         *     post-create).
         */
        UpdateTopologyProfileRequest: {
            name?: string | null;
            description?: string | null;
            category?: string | null;
            band?: string | null;
            frequency_mhz?: number | null;
            bandwidth_mhz?: number | null;
            scs_khz?: number | null;
            duplex?: string | null;
            arfcn?: number | null;
            mimo_layers?: number | null;
            mimo_port_preset?: string | null;
            dl_power_dbm?: number | null;
            ssb_power_dbm?: number | null;
            modulation?: string | null;
            target_mcs?: number | null;
            sched_algo?: string | null;
            enable_amc?: boolean | null;
            tdd_pattern?: string | null;
            tdd_period?: string | null;
            harq_max_trans?: number | null;
            harq_processes?: number | null;
            csi_rs_ports?: number | null;
            stat_count?: number | null;
            cell_id?: string | null;
            state_file?: string | null;
            compatible_test_apps?: string[] | null;
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
