/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get monitoring metric feeds */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Monitoring metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonitoringFeedsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List instrument categories and models */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Instrument catalog */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstrumentsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update instrument selection or connection */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateInstrumentPayload"];
                };
            };
            responses: {
                /** @description Updated category */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstrumentCategoryResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}/topology-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List operator-selectable topology profiles for a binding (P2-1)
         * @description Two-layer UXM architecture (P2-1 Phase 1):
         *     - Test App layer = SCPI command vocabulary, AUTO-DETECTED at
         *       connect via `SYSTem:APPLication:NAME?`. Operator does not pick.
         *     - Topology profile layer = cell/MIMO/power/FRC configuration
         *       within the running Test App. Operator-picked, persisted in
         *       `InstrumentConnection.connection_params['topology_profile_id']`,
         *       auto-applied on HAL reload.
         *     The `compatible_with_current_test_app` flag per item reflects
         *     the live HAL driver's detected_test_app — GUI greys out
         *     incompatible options. Empty `compatible_test_apps` on a profile
         *     means "compatible with any Test App" (no constraint).
         *     Only `baseStation` category exposes profiles today (UXM
         *     specific); other categories return empty + `reason="not_a_uxm"`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Topology profile list + live compat status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfilesListResult"];
                    };
                };
                /** @description Category not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Operator selects (or clears) the topology profile for a binding (P2-1)
         * @description - `profile_id=null` clears the selection.
         *     - `profile_id="known_id"` with no live driver: persists; takes
         *       effect on next HAL reload.
         *     - `profile_id="known_id"` + live driver + compatible: persists
         *       AND immediately applies on the driver. Response carries
         *       `applied_now=true`.
         *     - `profile_id="known_id"` + live driver + INCOMPATIBLE: returns
         *       409 with `refused: true` + structured reason. Binding is NOT
         *       persisted (refuses bail before DB write so operator can't
         *       save a doomed selection). Matches the P2-5 refuse pattern.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SelectTopologyProfileRequest"];
                };
            };
            responses: {
                /** @description Selection persisted (and optionally applied) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SelectTopologyProfileResult"];
                    };
                };
                /** @description Category, connection, or profile_id not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Topology incompatible with detected Test App */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Create a new operator-owned topology profile (P2-1 Phase 2.1)
         * @description `profile_id` is auto-allocated (`custom_<slug>`) — operators
         *     don't pick raw IDs (prevents collisions with built-ins and
         *     slug-formatting surprises). Returns the full row including the
         *     assigned ID so the GUI can pre-select it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTopologyProfileRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfileDetail"];
                    };
                };
                /** @description Bad request — empty name or unknown field */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Category does not host topology profiles */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}/topology-profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full detail for a single topology profile (P2-1 Phase 2.2)
         * @description Returns the full 25+ field row so the GUI editor modal can
         *     populate the form. The list endpoint returns only the
         *     truncated `TopologyProfileEntry`; this endpoint returns the
         *     full `TopologyProfileDetail`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full profile detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfileDetail"];
                    };
                };
                /** @description Profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Update an operator-owned topology profile (P2-1 Phase 2.1)
         * @description Partial-update. Refuses `is_system_preset=true` rows with 409 —
         *     operator must duplicate first. Unknown field keys return 400.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTopologyProfileRequest"];
                };
            };
            responses: {
                /** @description Updated row */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfileDetail"];
                    };
                };
                /** @description Bad request — unknown field */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description System preset — duplicate to edit */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delete an operator-owned topology profile (P2-1 Phase 2.1)
         * @description Refuses `is_system_preset=true` rows with 409. Does NOT touch
         *     bindings — if a category has the profile bound via
         *     `connection_params['topology_profile_id']`, that selection
         *     silently becomes stale on next HAL reload (HAL warns + skips
         *     auto-apply). GUI should warn before delete if bindings exist.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description System preset — cannot delete */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}/topology-profiles/{profileId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone any topology profile into a new editable copy (P2-1 Phase 2.1)
         * @description Supported source for both system presets and operator-owned
         *     rows. The new copy has `is_system_preset=false` (always) and
         *     a `(副本)` suffix on the name so it's visually distinct in the
         *     dropdown. Useful for the GUI's "duplicate-to-edit" flow on a
         *     system preset.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New editable copy */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopologyProfileDetail"];
                    };
                };
                /** @description Source profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/hal/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * HAL composite readiness snapshot (P3-5)
         * @description Returns the snapshot built during the last HAL initialise / reload:
         *     per-driver rows (category, model, endpoint, status, detail, plus
         *     driver-specific `extras` like F64 firmware_version), the active
         *     LabProfile state, the active calibration certificate validity,
         *     and a DUT-attach placeholder. `available=false` means HAL is not
         *     initialised yet — the sub-sections carry placeholders, the GUI
         *     should render "HAL not ready" rather than consuming them as live.
         *     Sibling HAL endpoints (`/hal/status`, `/hal/reload`, `/hal/switch`)
         *     are not currently in this contract; the GUI consumes them via
         *     inline-typed `axios.get`. Bringing them under generated types is
         *     out of scope for P3-5.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Readiness snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HALReadinessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DashboardResponse: {
            systemStatus: components["schemas"]["SystemStatusItem"][];
            activeAlerts: components["schemas"]["AlertItem"][];
            liveMetrics: components["schemas"]["MetricItem"][];
        };
        MonitoringFeedsResponse: {
            feeds: components["schemas"]["MetricItem"][];
        };
        InstrumentsResponse: {
            categories: components["schemas"]["InstrumentCategory"][];
        };
        InstrumentCategoryResponse: {
            category: components["schemas"]["InstrumentCategory"];
        };
        UpdateInstrumentPayload: {
            modelId?: string | null;
            connection?: components["schemas"]["InstrumentConnection"];
        };
        SystemStatusItem: {
            label: string;
            value: string;
            detail: string;
        };
        AlertItem: {
            id: string;
            title: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            timestamp: string;
        };
        MetricItem: {
            id?: string;
            label: string;
            value: string;
            trend?: string;
        };
        InstrumentCategory: {
            key: string;
            label: string;
            description: string;
            tags?: string[];
            selectedModelId: string | null;
            connection: components["schemas"]["InstrumentConnection"];
            models: components["schemas"]["InstrumentModel"][];
        };
        InstrumentModel: {
            id: string;
            vendor: string;
            model: string;
            summary: string;
            interfaces: string[];
            capabilities: string[];
            /**
             * @description P2-3: canonical capability tokens this model CAN expose
             *     (per DriverClass.model_capabilities ClassVar). Distinct
             *     from the freeform datasheet-derived `capabilities` badges
             *     above. Empty list means either no real driver is
             *     registered for the model, or the driver intentionally
             *     declared no tokens. Used by GUI to gate plan-binding
             *     picks before HAL Reload (closes the P1-1 pre-flight gap
             *     of needing a connected driver to know what it'd support).
             * @default []
             */
            model_capabilities: string[];
            bandwidth?: string | null;
            channels?: string | null;
            /**
             * @description Catalog availability status.
             *     - `available`: real driver class registered + HAL can bring it up
             *     - `pending_dev`: catalog row exists but no real driver class
             *       is registered yet (`_convert_model` in `app/api/instrument.py`
             *       maps to this when `get_real_driver_class()` returns None).
             *       Distinct from `offline` (which means "driver registered but
             *       not currently reachable") — operators picking a model need to
             *       see these as two different states so they don't try to
             *       connect to a model that fundamentally has no driver.
             *     - `offline` / `reserved` / `maintenance`: operational states
             *       for driver-backed models.
             * @enum {string}
             */
            status: "available" | "reserved" | "maintenance" | "offline" | "pending_dev";
        };
        InstrumentConnection: {
            endpoint?: string | null;
            controller?: string | null;
            notes?: string | null;
        };
        /**
         * @description P3-5 composite snapshot. `available=false` means HAL is not
         *     initialised; sub-sections still carry valid shapes (with
         *     placeholder values) so the GUI never has to handle a 404 or
         *     missing-field path.
         */
        HALReadinessResponse: {
            available: boolean;
            drivers: components["schemas"]["DriverReadinessRow"][];
            lab_profile: components["schemas"]["LabProfileReadiness"];
            calibration: components["schemas"]["CalibrationReadiness"];
            dut_attach: components["schemas"]["DutAttachReadiness"];
            generated_at_iso: string;
        };
        DriverReadinessRow: {
            category: string;
            model: string;
            endpoint: string;
            /** @enum {string} */
            status: "ok" | "fail" | "skipped";
            detail: string;
            /**
             * @description Driver-specific metadata (string-keyed). F64 surfaces
             *     firmware_version / band_label / product_family from the
             *     parsed SYST:INFO? response (P3-4); other drivers return an
             *     empty object until they override `readiness_metadata()`.
             *     Field values may be null when a driver field is unpopulated.
             * @default {}
             */
            extras: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Active LabProfile state. `status` distinguishes "no profiles at
         *     all" (`missing`) from "profiles exist but none active"
         *     (`inactive`) — different operator next-steps.
         */
        LabProfileReadiness: {
            profile_id?: string | null;
            profile_name?: string | null;
            is_active: boolean;
            /** @enum {string} */
            status: "ok" | "inactive" | "missing" | "ambiguous";
            detail: string;
        };
        /**
         * @description Validity of the active lab's bound calibration certificate.
         *     `no_lab` (no lab to look at a cert through) is distinct from
         *     `missing` (lab exists but cert FK is NULL) — the former hints
         *     "set up lab first", the latter hints "run calibration".
         */
        CalibrationReadiness: {
            certificate_number?: string | null;
            valid_until_iso?: string | null;
            /** @enum {string} */
            status: "valid" | "expired" | "missing" | "no_lab";
            days_remaining?: number | null;
            detail: string;
        };
        /**
         * @description DUT-attach state — placeholder in this build. `status` is
         *     always `not_implemented` since no runtime model exists for
         *     "DUT present in chamber" (no probe-sensing / RFID / session
         *     table). Field is in the contract so future probe-sensing
         *     work can land without breaking the response shape.
         */
        DutAttachReadiness: {
            status: string;
            detail: string;
        };
        /**
         * @description P2-1: one row in the topology profile listing.
         *     `compatible_with_current_test_app` is null when there's no
         *     live driver to check against (HAL not initialised, mock mode,
         *     no UXM driver bound) — GUI should treat null as "unknown,
         *     allow selection but warn".
         */
        TopologyProfileEntry: {
            profile_id: string;
            name: string;
            description: string;
            category: string;
            compatible_test_apps: string[];
            compatible_with_current_test_app?: boolean | null;
            /**
             * @description P2-1 Phase 2.1: true for the 7 built-ins seeded by the
             *     bootstrap seeder. GUI renders these as read-only with a
             *     'duplicate to edit' affordance (clone-to-edit pattern).
             */
            is_system_preset?: boolean;
        };
        TopologyProfilesListResult: {
            items: components["schemas"]["TopologyProfileEntry"][];
            current_test_app?: string | null;
            selected_topology_profile_id?: string | null;
            /**
             * @description `"not_a_uxm"` when the category doesn't host topology
             *     profiles (today everything except baseStation); otherwise
             *     null. Future categories (CMX500 etc.) extend the dispatch
             *     in `_list_topology_profiles_for_category`.
             */
            reason?: string | null;
        };
        SelectTopologyProfileRequest: {
            /**
             * @description Topology profile ID to bind to this category. Null clears
             *     the selection so HAL reload won't auto-apply anything.
             */
            profile_id?: string | null;
        };
        SelectTopologyProfileResult: {
            persisted: boolean;
            profile_id?: string | null;
            applied_now: boolean;
            /**
             * @description Non-null when the binding was persisted but the driver
             *     was NOT live-applied. Values: `no_selection` (cleared),
             *     `no_live_driver` (HAL not initialised), `driver_does_not_support_topology_profiles`
             *     (e.g. mock driver), `incompatible_test_app` (compat check
             *     failed at the driver level — usually caught earlier as 409).
             */
            apply_skipped_reason?: string | null;
            test_app?: string | null;
        };
        /**
         * @description P2-1 Phase 2.1: full topology profile row returned by CRUD
         *     endpoints (create / update / duplicate). Mirrors the
         *     `UxmTestProfile` dataclass + DB columns.
         */
        TopologyProfileDetail: {
            profile_id: string;
            name: string;
            description?: string | null;
            category: string;
            band: string;
            frequency_mhz: number;
            bandwidth_mhz: number;
            scs_khz: number;
            duplex: string;
            arfcn?: number | null;
            mimo_layers: number;
            mimo_port_preset: string;
            dl_power_dbm: number;
            ssb_power_dbm: number;
            modulation: string;
            target_mcs: number;
            sched_algo: string;
            enable_amc: boolean;
            tdd_pattern: string;
            tdd_period: string;
            harq_max_trans: number;
            harq_processes: number;
            csi_rs_ports?: number | null;
            stat_count: number;
            cell_id: string;
            state_file?: string | null;
            compatible_test_apps: string[];
            notes?: string | null;
            is_system_preset: boolean;
            created_by?: string | null;
        };
        /**
         * @description P2-1 Phase 2.1: POST payload. `name` required; everything else
         *     falls back to dataclass defaults. profile_id is auto-allocated
         *     as `custom_<slug>` so the operator doesn't pick raw IDs.
         */
        CreateTopologyProfileRequest: {
            name: string;
            description?: string | null;
            category?: string | null;
            band?: string | null;
            frequency_mhz?: number | null;
            bandwidth_mhz?: number | null;
            scs_khz?: number | null;
            duplex?: string | null;
            arfcn?: number | null;
            mimo_layers?: number | null;
            mimo_port_preset?: string | null;
            dl_power_dbm?: number | null;
            ssb_power_dbm?: number | null;
            modulation?: string | null;
            target_mcs?: number | null;
            sched_algo?: string | null;
            enable_amc?: boolean | null;
            tdd_pattern?: string | null;
            tdd_period?: string | null;
            harq_max_trans?: number | null;
            harq_processes?: number | null;
            csi_rs_ports?: number | null;
            stat_count?: number | null;
            cell_id?: string | null;
            state_file?: string | null;
            compatible_test_apps?: string[] | null;
            notes?: string | null;
            created_by?: string | null;
        };
        /**
         * @description P2-1 Phase 2.1: PUT payload — all fields optional. Same field
         *     allowlist as Create minus `created_by` (audit field, immutable
         *     post-create).
         */
        UpdateTopologyProfileRequest: {
            name?: string | null;
            description?: string | null;
            category?: string | null;
            band?: string | null;
            frequency_mhz?: number | null;
            bandwidth_mhz?: number | null;
            scs_khz?: number | null;
            duplex?: string | null;
            arfcn?: number | null;
            mimo_layers?: number | null;
            mimo_port_preset?: string | null;
            dl_power_dbm?: number | null;
            ssb_power_dbm?: number | null;
            modulation?: string | null;
            target_mcs?: number | null;
            sched_algo?: string | null;
            enable_amc?: boolean | null;
            tdd_pattern?: string | null;
            tdd_period?: string | null;
            harq_max_trans?: number | null;
            harq_processes?: number | null;
            csi_rs_ports?: number | null;
            stat_count?: number | null;
            cell_id?: string | null;
            state_file?: string | null;
            compatible_test_apps?: string[] | null;
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
