/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get monitoring metric feeds */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Monitoring metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonitoringFeedsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List instrument categories and models */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Instrument catalog */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstrumentsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{categoryKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update instrument selection or connection */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryKey: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateInstrumentPayload"];
                };
            };
            responses: {
                /** @description Updated category */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstrumentCategoryResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/hal/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * HAL composite readiness snapshot (P3-5)
         * @description Returns the snapshot built during the last HAL initialise / reload:
         *     per-driver rows (category, model, endpoint, status, detail, plus
         *     driver-specific `extras` like F64 firmware_version), the active
         *     LabProfile state, the active calibration certificate validity,
         *     and a DUT-attach placeholder. `available=false` means HAL is not
         *     initialised yet — the sub-sections carry placeholders, the GUI
         *     should render "HAL not ready" rather than consuming them as live.
         *     Sibling HAL endpoints (`/hal/status`, `/hal/reload`, `/hal/switch`)
         *     are not currently in this contract; the GUI consumes them via
         *     inline-typed `axios.get`. Bringing them under generated types is
         *     out of scope for P3-5.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Readiness snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HALReadinessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DashboardResponse: {
            systemStatus: components["schemas"]["SystemStatusItem"][];
            activeAlerts: components["schemas"]["AlertItem"][];
            liveMetrics: components["schemas"]["MetricItem"][];
        };
        MonitoringFeedsResponse: {
            feeds: components["schemas"]["MetricItem"][];
        };
        InstrumentsResponse: {
            categories: components["schemas"]["InstrumentCategory"][];
        };
        InstrumentCategoryResponse: {
            category: components["schemas"]["InstrumentCategory"];
        };
        UpdateInstrumentPayload: {
            modelId?: string | null;
            connection?: components["schemas"]["InstrumentConnection"];
        };
        SystemStatusItem: {
            label: string;
            value: string;
            detail: string;
        };
        AlertItem: {
            id: string;
            title: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            timestamp: string;
        };
        MetricItem: {
            id?: string;
            label: string;
            value: string;
            trend?: string;
        };
        InstrumentCategory: {
            key: string;
            label: string;
            description: string;
            tags?: string[];
            selectedModelId: string | null;
            connection: components["schemas"]["InstrumentConnection"];
            models: components["schemas"]["InstrumentModel"][];
        };
        InstrumentModel: {
            id: string;
            vendor: string;
            model: string;
            summary: string;
            interfaces: string[];
            capabilities: string[];
            /**
             * @description P2-3: canonical capability tokens this model CAN expose
             *     (per DriverClass.model_capabilities ClassVar). Distinct
             *     from the freeform datasheet-derived `capabilities` badges
             *     above. Empty list means either no real driver is
             *     registered for the model, or the driver intentionally
             *     declared no tokens. Used by GUI to gate plan-binding
             *     picks before HAL Reload (closes the P1-1 pre-flight gap
             *     of needing a connected driver to know what it'd support).
             * @default []
             */
            model_capabilities: string[];
            bandwidth?: string | null;
            channels?: string | null;
            /**
             * @description Catalog availability status.
             *     - `available`: real driver class registered + HAL can bring it up
             *     - `pending_dev`: catalog row exists but no real driver class
             *       is registered yet (`_convert_model` in `app/api/instrument.py`
             *       maps to this when `get_real_driver_class()` returns None).
             *       Distinct from `offline` (which means "driver registered but
             *       not currently reachable") — operators picking a model need to
             *       see these as two different states so they don't try to
             *       connect to a model that fundamentally has no driver.
             *     - `offline` / `reserved` / `maintenance`: operational states
             *       for driver-backed models.
             * @enum {string}
             */
            status: "available" | "reserved" | "maintenance" | "offline" | "pending_dev";
        };
        InstrumentConnection: {
            endpoint?: string | null;
            controller?: string | null;
            notes?: string | null;
        };
        /**
         * @description P3-5 composite snapshot. `available=false` means HAL is not
         *     initialised; sub-sections still carry valid shapes (with
         *     placeholder values) so the GUI never has to handle a 404 or
         *     missing-field path.
         */
        HALReadinessResponse: {
            available: boolean;
            drivers: components["schemas"]["DriverReadinessRow"][];
            lab_profile: components["schemas"]["LabProfileReadiness"];
            calibration: components["schemas"]["CalibrationReadiness"];
            dut_attach: components["schemas"]["DutAttachReadiness"];
            generated_at_iso: string;
        };
        DriverReadinessRow: {
            category: string;
            model: string;
            endpoint: string;
            /** @enum {string} */
            status: "ok" | "fail" | "skipped";
            detail: string;
            /**
             * @description Driver-specific metadata (string-keyed). F64 surfaces
             *     firmware_version / band_label / product_family from the
             *     parsed SYST:INFO? response (P3-4); other drivers return an
             *     empty object until they override `readiness_metadata()`.
             *     Field values may be null when a driver field is unpopulated.
             * @default {}
             */
            extras: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Active LabProfile state. `status` distinguishes "no profiles at
         *     all" (`missing`) from "profiles exist but none active"
         *     (`inactive`) — different operator next-steps.
         */
        LabProfileReadiness: {
            profile_id?: string | null;
            profile_name?: string | null;
            is_active: boolean;
            /** @enum {string} */
            status: "ok" | "inactive" | "missing" | "ambiguous";
            detail: string;
        };
        /**
         * @description Validity of the active lab's bound calibration certificate.
         *     `no_lab` (no lab to look at a cert through) is distinct from
         *     `missing` (lab exists but cert FK is NULL) — the former hints
         *     "set up lab first", the latter hints "run calibration".
         */
        CalibrationReadiness: {
            certificate_number?: string | null;
            valid_until_iso?: string | null;
            /** @enum {string} */
            status: "valid" | "expired" | "missing" | "no_lab";
            days_remaining?: number | null;
            detail: string;
        };
        /**
         * @description DUT-attach state — placeholder in this build. `status` is
         *     always `not_implemented` since no runtime model exists for
         *     "DUT present in chamber" (no probe-sensing / RFID / session
         *     table). Field is in the contract so future probe-sensing
         *     work can land without breaking the response shape.
         */
        DutAttachReadiness: {
            status: string;
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
