"""Alert database models"""
from sqlalchemy import Column, String, Boolean, DateTime, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
import uuid
import enum

from app.db.database import Base


class AlertSeverity(str, enum.Enum):
    """Alert severity levels"""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class AlertStatus(str, enum.Enum):
    """Alert status"""
    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    DISMISSED = "dismissed"


class Alert(Base):
    """
    Alert - System alerts and notifications

    Alerts are generated by the system to notify users of important events,
    warnings, errors, or critical conditions that require attention.
    """
    __tablename__ = "alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Alert content
    title = Column(String(255), nullable=False, comment="Alert title")
    message = Column(Text, nullable=True, comment="Detailed alert message")

    # Classification
    severity = Column(
        String(20),
        nullable=False,
        default=AlertSeverity.INFO.value,
        comment="Alert severity: info | warning | error | critical"
    )
    alert_type = Column(String(100), nullable=True, comment="Alert category/type")
    source = Column(String(100), nullable=True, comment="Source system/component")

    # Status tracking
    status = Column(
        String(20),
        nullable=False,
        default=AlertStatus.ACTIVE.value,
        comment="Alert status: active | acknowledged | resolved | dismissed"
    )
    is_read = Column(Boolean, default=False, comment="Whether alert has been read")

    # Context
    related_entity_type = Column(String(100), nullable=True, comment="Related entity type (test_plan, probe, etc.)")
    related_entity_id = Column(UUID(as_uuid=True), nullable=True, comment="Related entity UUID")
    extra_data = Column(Text, nullable=True, comment="JSON metadata for additional context")

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)

    # User tracking
    created_by = Column(String(255), nullable=True, comment="User or system that created the alert")
    acknowledged_by = Column(String(255), nullable=True, comment="User who acknowledged the alert")
