/**
 * Scenario to Test Plan Conversion Utility
 *
 * Converts a Road Test Scenario into a Test Plan with auto-generated steps
 * Part of Phase 4.1: System Integration
 */

import type { RoadTestScenario, ScenarioSummary } from '../types/roadTest'
import type { CreatePlanPayload } from '../types/api'

/**
 * Generate Test Plan from Road Test Scenario
 *
 * Creates a test plan with 7 auto-generated steps based on scenario configuration
 */
export function generateTestPlanFromScenario(
  scenario: ScenarioSummary | RoadTestScenario
): CreatePlanPayload {
  // Extract max velocity from scenario if available
  const maxVelocity = 'route' in scenario && scenario.route?.waypoints
    ? Math.max(...scenario.route.waypoints.map((wp: any) => wp.velocity?.speed_kmh || 0))
    : 50 // Default 50 km/h

  return {
    name: `${scenario.name} - Test Plan`,
    description: scenario.description || `Auto-generated test plan from scenario: ${scenario.name}`,
    version: '1.0',
    priority: 5,

    // Link to source scenario
    scenario_id: scenario.id,

    // DUT info (user will complete)
    dut_info: {
      model: 'TBD',
      serial_number: 'TBD',
      imei: null,
    },

    // Copy environment settings from scenario
    test_environment: {
      chamber_id: 'MPAC-1',
      temperature_c: 25,
      humidity_percent: 50,
      // Add scenario-specific environment
      ...(('environment' in scenario && scenario.environment) ? {
        channel_model: scenario.environment.channel_model,
        environment_type: scenario.environment.type,
      } : {}),
      ...(('route' in scenario && scenario.route) ? {
        route_type: scenario.route.type,
        duration_s: scenario.route.duration_s,
        total_distance_m: scenario.route.total_distance_m,
      } : {
        duration_s: scenario.duration_s,
        total_distance_m: scenario.distance_m,
      }),
    },

    // Generate test steps (will be added separately via API)
    test_case_ids: [],

    created_by: 'system', // Auto-generated by system

    notes: `Auto-generated from Virtual Road Test scenario: ${scenario.id}`,

    tags: [
      'auto-generated',
      'road-test',
      scenario.category,
      ...(scenario.tags || []),
    ],
  }
}

/**
 * Generate step descriptions based on scenario
 */
export function generateStepDescriptions(scenario: ScenarioSummary): string[] {
  return [
    `Initialize OTA Chamber (MPAC) for ${scenario.name}`,
    `Configure Network: ${scenario.category} test`,
    `Setup Base Stations and Channel Model`,
    `Configure OTA Mapper for scenario ${scenario.id}`,
    `Execute Route Test (Duration: ${Math.round(scenario.duration_s)}s, Distance: ${Math.round(scenario.distance_m)}m)`,
    `Validate KPIs and Performance Metrics`,
    `Generate Test Report`,
  ]
}

/**
 * Validate scenario can be converted to test plan
 */
export function canConvertToTestPlan(scenario: ScenarioSummary): {
  canConvert: boolean
  reason?: string
} {
  // Check if scenario has required fields
  if (!scenario.id) {
    return { canConvert: false, reason: 'Scenario missing ID' }
  }

  if (!scenario.name || scenario.name.trim().length === 0) {
    return { canConvert: false, reason: 'Scenario missing name' }
  }

  if (scenario.duration_s <= 0) {
    return { canConvert: false, reason: 'Invalid scenario duration' }
  }

  return { canConvert: true }
}

/**
 * Get estimated test plan duration
 */
export function estimateTestPlanDuration(scenario: ScenarioSummary): number {
  // Base duration: scenario duration + setup/teardown overhead
  const setupTime = 10 // 10 minutes for chamber init + network config
  const teardownTime = 5 // 5 minutes for report generation
  const scenarioDurationMinutes = scenario.duration_s / 60

  return Math.ceil(setupTime + scenarioDurationMinutes + teardownTime)
}
