"""Template Rendering Service for Reports

This module renders report templates using Jinja2 template engine.
Supports dynamic content generation with variable substitution.
"""
import logging
from typing import Dict, List, Any, Optional
from jinja2 import Environment, Template, TemplateError
from datetime import datetime

logger = logging.getLogger(__name__)


class TemplateRenderer:
    """Service for rendering report templates"""

    def __init__(self):
        # Create Jinja2 environment
        self.env = Environment(
            autoescape=True,
            trim_blocks=True,
            lstrip_blocks=True
        )

        # Add custom filters
        self.env.filters['format_date'] = self._format_date
        self.env.filters['format_number'] = self._format_number
        self.env.filters['format_percentage'] = self._format_percentage

    def render_template(
        self,
        template_string: str,
        context: Dict[str, Any]
    ) -> str:
        """
        Render a template string with context data

        Args:
            template_string: Jinja2 template string
            context: Dictionary of variables to substitute

        Returns:
            Rendered template string
        """
        try:
            template = self.env.from_string(template_string)
            rendered = template.render(**context)
            logger.debug(f"Template rendered successfully with context keys: {list(context.keys())}")
            return rendered

        except TemplateError as e:
            logger.error(f"Template rendering error: {e}")
            raise ValueError(f"Failed to render template: {e}")

    def render_section(
        self,
        section_config: Dict[str, Any],
        data: Dict[str, Any]
    ) -> str:
        """
        Render a report section based on configuration

        Args:
            section_config: Section configuration from template
            data: Test execution data

        Returns:
            Rendered section HTML/text
        """
        section_type = section_config.get('type', 'text')

        if section_type == 'cover':
            return self._render_cover(section_config, data)
        elif section_type == 'text':
            return self._render_text(section_config, data)
        elif section_type == 'table':
            return self._render_table(section_config, data)
        elif section_type == 'mixed':
            return self._render_mixed(section_config, data)
        else:
            logger.warning(f"Unknown section type: {section_type}")
            return ""

    def _render_cover(
        self,
        config: Dict[str, Any],
        data: Dict[str, Any]
    ) -> str:
        """Render cover page section"""
        template_str = """
        <div class="cover-page">
            <h1>{{ title }}</h1>
            {% if subtitle %}<h2>{{ subtitle }}</h2>{% endif %}
            <div class="metadata">
                <p><strong>Date:</strong> {{ date }}</p>
                <p><strong>Test Plan:</strong> {{ test_plan_name }}</p>
                {% if dut_info %}<p><strong>DUT:</strong> {{ dut_info }}</p>{% endif %}
                {% if generated_by %}<p><strong>Generated By:</strong> {{ generated_by }}</p>{% endif %}
            </div>
        </div>
        """

        context = {
            'title': data.get('title', 'Test Report'),
            'subtitle': data.get('subtitle', ''),
            'date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'test_plan_name': data.get('test_plan_name', 'N/A'),
            'dut_info': data.get('dut_info', ''),
            'generated_by': data.get('generated_by', 'System')
        }

        return self.render_template(template_str, context)

    def _render_text(
        self,
        config: Dict[str, Any],
        data: Dict[str, Any]
    ) -> str:
        """Render text section with template variables"""
        template_str = config.get('content_template', '')

        if not template_str:
            template_str = "<h2>{{ section_title }}</h2><p>{{ content }}</p>"

        context = {
            'section_title': config.get('title', ''),
            'content': data.get('content', ''),
            **data  # Include all data for flexible templating
        }

        return self.render_template(template_str, context)

    def _render_table(
        self,
        config: Dict[str, Any],
        data: Dict[str, Any]
    ) -> str:
        """Render table section"""
        template_str = """
        <div class="table-section">
            <h2>{{ title }}</h2>
            <table class="data-table">
                <thead>
                    <tr>
                        {% for field in fields %}
                        <th>{{ field }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for row in rows %}
                    <tr>
                        {% for field in fields %}
                        <td>{{ row.get(field, 'N/A') }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        """

        fields = config.get('fields', [])
        rows = data.get('table_data', [])

        context = {
            'title': config.get('title', 'Data Table'),
            'fields': fields,
            'rows': rows
        }

        return self.render_template(template_str, context)

    def _render_mixed(
        self,
        config: Dict[str, Any],
        data: Dict[str, Any]
    ) -> str:
        """Render mixed content (text + charts + tables)"""
        sections = []

        # Add text description if present
        if 'description' in data:
            sections.append(f"<p>{data['description']}</p>")

        # Add charts
        if config.get('include_charts', False):
            sections.append('<div class="charts-container">')
            for chart_id in data.get('chart_ids', []):
                sections.append(f'<div class="chart"><img src="{chart_id}" /></div>')
            sections.append('</div>')

        # Add tables
        if config.get('include_tables', False) and 'table_data' in data:
            table_config = {'title': config.get('title', ''), 'fields': config.get('fields', [])}
            sections.append(self._render_table(table_config, data))

        return '\n'.join(sections)

    def render_comparison_section(
        self,
        baseline_data: Dict[str, Any],
        comparison_data: List[Dict[str, Any]],
        metrics: List[str]
    ) -> str:
        """
        Render comparison analysis section

        Args:
            baseline_data: Baseline test data
            comparison_data: List of comparison test data
            metrics: List of metrics to compare

        Returns:
            Rendered comparison HTML
        """
        template_str = """
        <div class="comparison-section">
            <h2>Performance Comparison</h2>
            <table class="comparison-table">
                <thead>
                    <tr>
                        <th>Metric</th>
                        <th>Baseline</th>
                        {% for comp in comparisons %}
                        <th>{{ comp.name }}</th>
                        {% endfor %}
                        <th>Best</th>
                    </tr>
                </thead>
                <tbody>
                    {% for metric in metrics %}
                    <tr>
                        <td>{{ metric }}</td>
                        <td>{{ baseline.get(metric, 'N/A') }}</td>
                        {% for comp in comparisons %}
                        <td>{{ comp.data.get(metric, 'N/A') }}</td>
                        {% endfor %}
                        <td class="highlight">{{ best_values.get(metric, 'N/A') }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        """

        # Calculate best values for each metric
        best_values = {}
        for metric in metrics:
            values = [baseline_data.get(metric, 0)]
            values.extend([comp.get(metric, 0) for comp in comparison_data])
            best_values[metric] = max(values)

        context = {
            'metrics': metrics,
            'baseline': baseline_data,
            'comparisons': [{'name': f"Test {i+1}", 'data': comp} for i, comp in enumerate(comparison_data)],
            'best_values': best_values
        }

        return self.render_template(template_str, context)

    # Custom Jinja2 filters

    def _format_date(self, value, format_str='%Y-%m-%d %H:%M:%S'):
        """Format datetime object to string"""
        if isinstance(value, datetime):
            return value.strftime(format_str)
        elif isinstance(value, str):
            return value
        else:
            return str(value)

    def _format_number(self, value, decimals=2):
        """Format number with specified decimal places"""
        try:
            return f"{float(value):.{decimals}f}"
        except (ValueError, TypeError):
            return str(value)

    def _format_percentage(self, value, decimals=1):
        """Format number as percentage"""
        try:
            return f"{float(value)*100:.{decimals}f}%"
        except (ValueError, TypeError):
            return str(value)
